lr: 1.0e-3
lr_end: 1.0e-5
opt_eps: 1.0e-8
n_epochs: 2000
grad_norm: 0
eval_epochs: 50
batch_size: 16
cuda: true
smoothing: 20
freq_cut_off: 10000
sim_obs_noise: 0
sim_latent_noise: 1
k: 64
loss_f: VGTF
resample: systematic # multinomial or none
observation_likelihood: Poisson # observation likelihood
t_forward: ${dataset.t_forward}
run_eval: false
